import { Extension } from "@tiptap/core";
import { Plugin, PluginKey } from "@tiptap/pm/state";
import { Decoration, DecorationSet } from "@tiptap/pm/view";
import type { Node as ProseMirrorNode } from "@tiptap/pm/model";

// Bullet/number markers (`::marker`) are generated by the browser from the
// <li> element's own computed style — they do NOT inherit from a styled
// <span> nested inside the item's text, which is how this editor actually
// applies text colour/font family/font size (all three are attributes on
// the shared `textStyle` mark — see extensions/FontSize.ts). Without this
// plugin a list item's marker always renders in Typography's fixed
// `--tw-prose-bullets`/`--tw-prose-counters` colour, in the body font, at
// the body size, no matter what colour/font/size is applied to the item's
// own text — which reads as those options silently not working on lists.
//
// This walks the document for `listItem` nodes on every doc change (not
// on every selection change — see the `state.apply` guard below, the same
// "only recompute what actually changed" discipline the Story Graph's own
// memos already follow) and reads the `textStyle` mark off the *first*
// text run inside each item's own first paragraph (never descending into
// a nested sub-list's text — a list item's marker should reflect that
// item's own styling, not a child list's). A decoration then sets three
// CSS custom properties directly on the <li>'s inline style —
// `--marker-color`/`--marker-font`/`--marker-size` — which styles/index.css
// feeds into `::marker` via `var(...)`. Bold/italic/underline are
// deliberately left out (existing markers already render in the app's
// normal marker weight/style, and the request was specifically to leave
// those three alone); background colour is left out too, because
// `::marker` does not accept `background-color` at all per the CSS spec —
// no CSS trick makes a real background render behind a native marker
// glyph, so faking one isn't attempted here.
const pluginKey = new PluginKey<DecorationSet>("markerStyleSync");

function firstTextStyleAttrs(paragraph: ProseMirrorNode): { color?: string; fontFamily?: string; fontSize?: string } | null {
  let found: { color?: string; fontFamily?: string; fontSize?: string } | null = null;
  paragraph.descendants((child) => {
    if (found) return false;
    if (child.isText && child.text) {
      const textStyle = child.marks.find((m) => m.type.name === "textStyle");
      if (textStyle) {
        const { color, fontFamily, fontSize } = textStyle.attrs as {
          color?: string | null;
          fontFamily?: string | null;
          fontSize?: string | null;
        };
        if (color || fontFamily || fontSize) {
          found = {
            ...(color ? { color } : {}),
            ...(fontFamily ? { fontFamily } : {}),
            ...(fontSize ? { fontSize } : {}),
          };
        } else {
          found = {};
        }
      } else {
        found = {};
      }
      return false;
    }
    return true;
  });
  return found;
}

function buildDecorations(doc: ProseMirrorNode): DecorationSet {
  const decorations: Decoration[] = [];

  doc.descendants((node, pos) => {
    if (node.type.name !== "listItem") return true;

    const firstBlock = node.childCount > 0 ? node.child(0) : null;
    if (firstBlock && firstBlock.isTextblock) {
      const attrs = firstTextStyleAttrs(firstBlock);
      if (attrs && (attrs.color || attrs.fontFamily || attrs.fontSize)) {
        const styleParts: string[] = [];
        if (attrs.color) styleParts.push(`--marker-color: ${attrs.color}`);
        if (attrs.fontFamily) styleParts.push(`--marker-font: ${attrs.fontFamily}`);
        if (attrs.fontSize) styleParts.push(`--marker-size: ${attrs.fontSize}`);
        decorations.push(
          Decoration.node(pos, pos + node.nodeSize, { style: styleParts.join("; ") })
        );
      }
    }
    return true;
  });

  return DecorationSet.create(doc, decorations);
}

export const MarkerStyleSync = Extension.create({
  name: "markerStyleSync",

  addProseMirrorPlugins() {
    return [
      new Plugin({
        key: pluginKey,
        state: {
          init: (_, state) => buildDecorations(state.doc),
          apply: (tr, old) => (tr.docChanged ? buildDecorations(tr.doc) : old),
        },
        props: {
          decorations(state) {
            return pluginKey.getState(state);
          },
        },
      }),
    ];
  },
});
